### ISSUE TITLE
Improve and increase build automation for new releases

### ISSUE THREAD

**Issue by timothycrosley** [hugapi/hug#297]
While some automation is currently in place within the projects autoenv (see `new_version` and `distribute`), long-term hug could benefit from a more automated build system, where tagged passing released automatically get deployed to PYPI and new docker images could be built automatically.

A tool like https://github.com/vortec/versionbump or https://pypi.python.org/pypi/bumpversion could be used to automate the semantic version increments.

see https://docs.docker.com/docker-hub/builds/ for more information on automating docker image builds

**Comment by butla** [comment]
I don't know if that was what you meant, but I've just created PR #407 (oh the sweet, sweet Hacktoberfest credit).

When it comes to automating releases, I think that a commit convention like [Angular's](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines) can be a big help.
If you use semantic versioning and write down whether a commit is a fix, a new feature, or whatever, it can be quite straightforward to automatically create new releases (because you know whether you need one or not). A bit of shameless self-marketing: I've created an [article about that](https://bultrowicz.com/cd-with-angularjs-commits/)

I'm also using SnapCI there. Don't know if it's a good fit for you, but tagging can be implemented as a manual step in a pipeline (if you don't have absolute trust in the automated tests)
