### ISSUE TITLE
Falkon version

### ISSUE THREAD

**Issue by somenxavier** [hugapi/hug#831]
I [try](https://bbs.archlinux.org/viewtopic.php?pid=1874383#p1874383) to make a arch package but it seems your software needs specific falkon version (2.0.0) instead modern one (nowadays 3.1.0) It there any reason for that? Can we replace `falkon == 2.0.0` with `falkon >=2.0.0` in [common file](https://github.com/hugapi/hug/blob/develop/requirements/common.txt)

**Comment by timothycrosley** [comment]
Hi @somenxavier,

I'm a little confused, the official latest version of Falcon *is* 2.0.0 see:

https://pypi.org/project/falcon/#history

There's a lot of compatibility that needs to be confirmed between releases and that's why the version is pinned. However, this project is very quick to make those compatibility changes when a new release does indeed occur, and we coordinate with the Falcon team to ensure compatibility. 

Thanks!

~Timothy

**Comment by somenxavier** [comment]
My fault: I confuse `falcon` with `falkon`. Sorry
